// Generated by CoffeeScript 1.9.1
(function() {
  this.ISFGL = (function() {
    function ISFGL() {}

    ISFGL.init = function(gl) {
      ISFGL.gl = gl;
      return ISFGL.textureIndex = 0;
    };

    ISFGL.newTextureIndex = function() {
      var i;
      i = ISFGL.textureIndex;
      ISFGL.textureIndex += 1;
      return i;
    };

    ISFGL.cleanup = function() {
      return ISFGL.textureIndex = 0;
    };

    return ISFGL;

  })();

}).call(this);
